name: qardqntac-production

services:
  app:
    build:
      context: .
      dockerfile: docker/dockerfile
      target: prod
#    image: occos/qardqntac:latest
    container_name: qardqntac-production-app
    restart: unless-stopped
    ports:
      - "7658:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    container_name: qardqntac-production-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - qardqntac_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  qardqntac_postgres_data:
